// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace GE.WebAdmin.Controllers
{
    public partial class VideoLinksController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected VideoLinksController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult Index()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult IndexNotlinked()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.IndexNotlinked);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.RedirectResult AddMaterialVideo()
        {
            return new T4MVC_System_Web_Mvc_RedirectResult(Area, Name, ActionNames.AddMaterialVideo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.RedirectToRouteResult DeleteMaterialVideo()
        {
            return new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.DeleteMaterialVideo);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public VideoLinksController Actions { get { return MVC.VideoLinks; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "VideoLinks";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "VideoLinks";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string IndexNotlinked = "IndexNotlinked";
            public readonly string AddMaterialVideo = "AddMaterialVideo";
            public readonly string DeleteMaterialVideo = "DeleteMaterialVideo";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string IndexNotlinked = "IndexNotlinked";
            public const string AddMaterialVideo = "AddMaterialVideo";
            public const string DeleteMaterialVideo = "DeleteMaterialVideo";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string mid = "mid";
            public readonly string mct = "mct";
            public readonly string fm = "fm";
            public readonly string page = "page";
            public readonly string filterModel = "filterModel";
            public readonly string order = "order";
        }
        static readonly ActionParamsClass_IndexNotlinked s_params_IndexNotlinked = new ActionParamsClass_IndexNotlinked();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IndexNotlinked IndexNotlinkedParams { get { return s_params_IndexNotlinked; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IndexNotlinked
        {
            public readonly string mid = "mid";
            public readonly string mct = "mct";
            public readonly string fm = "fm";
            public readonly string page = "page";
            public readonly string filterModel = "filterModel";
            public readonly string order = "order";
        }
        static readonly ActionParamsClass_AddMaterialVideo s_params_AddMaterialVideo = new ActionParamsClass_AddMaterialVideo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddMaterialVideo AddMaterialVideoParams { get { return s_params_AddMaterialVideo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddMaterialVideo
        {
            public readonly string mid = "mid";
            public readonly string mct = "mct";
        }
        static readonly ActionParamsClass_DeleteMaterialVideo s_params_DeleteMaterialVideo = new ActionParamsClass_DeleteMaterialVideo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteMaterialVideo DeleteMaterialVideoParams { get { return s_params_DeleteMaterialVideo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteMaterialVideo
        {
            public readonly string mid = "mid";
            public readonly string mct = "mct";
            public readonly string vid = "vid";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _GridView = "_GridView";
                public readonly string _GridViewNotLinked = "_GridViewNotLinked";
            }
            public readonly string _GridView = "~/Views/VideoLinks/_GridView.cshtml";
            public readonly string _GridViewNotLinked = "~/Views/VideoLinks/_GridViewNotLinked.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_VideoLinksController : GE.WebAdmin.Controllers.VideoLinksController
    {
        public T4MVC_VideoLinksController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int mid, SX.WebCore.Enums.ModelCoreType mct, bool fm, int page);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult Index(int mid, SX.WebCore.Enums.ModelCoreType mct, bool fm, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mid", mid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mct", mct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fm", fm);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            IndexOverride(callInfo, mid, mct, fm, page);
            return callInfo;
        }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int mid, SX.WebCore.Enums.ModelCoreType mct, GE.WebAdmin.Models.VMVideo filterModel, System.Collections.Generic.IDictionary<string, SX.WebCore.HtmlHelpers.SxExtantions.SortDirection> order, bool fm, int page);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult Index(int mid, SX.WebCore.Enums.ModelCoreType mct, GE.WebAdmin.Models.VMVideo filterModel, System.Collections.Generic.IDictionary<string, SX.WebCore.HtmlHelpers.SxExtantions.SortDirection> order, bool fm, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mid", mid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mct", mct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filterModel", filterModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "order", order);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fm", fm);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            IndexOverride(callInfo, mid, mct, filterModel, order, fm, page);
            return callInfo;
        }

        [NonAction]
        partial void IndexNotlinkedOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int mid, SX.WebCore.Enums.ModelCoreType mct, bool fm, int page);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult IndexNotlinked(int mid, SX.WebCore.Enums.ModelCoreType mct, bool fm, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.IndexNotlinked);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mid", mid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mct", mct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fm", fm);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            IndexNotlinkedOverride(callInfo, mid, mct, fm, page);
            return callInfo;
        }

        [NonAction]
        partial void IndexNotlinkedOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int mid, SX.WebCore.Enums.ModelCoreType mct, GE.WebAdmin.Models.VMVideo filterModel, System.Collections.Generic.IDictionary<string, SX.WebCore.HtmlHelpers.SxExtantions.SortDirection> order, bool fm, int page);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult IndexNotlinked(int mid, SX.WebCore.Enums.ModelCoreType mct, GE.WebAdmin.Models.VMVideo filterModel, System.Collections.Generic.IDictionary<string, SX.WebCore.HtmlHelpers.SxExtantions.SortDirection> order, bool fm, int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.IndexNotlinked);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mid", mid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mct", mct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "filterModel", filterModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "order", order);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fm", fm);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            IndexNotlinkedOverride(callInfo, mid, mct, filterModel, order, fm, page);
            return callInfo;
        }

        [NonAction]
        partial void AddMaterialVideoOverride(T4MVC_System_Web_Mvc_RedirectResult callInfo, int mid, SX.WebCore.Enums.ModelCoreType mct);

        [NonAction]
        public override System.Web.Mvc.RedirectResult AddMaterialVideo(int mid, SX.WebCore.Enums.ModelCoreType mct)
        {
            var callInfo = new T4MVC_System_Web_Mvc_RedirectResult(Area, Name, ActionNames.AddMaterialVideo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mid", mid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mct", mct);
            AddMaterialVideoOverride(callInfo, mid, mct);
            return callInfo;
        }

        [NonAction]
        partial void DeleteMaterialVideoOverride(T4MVC_System_Web_Mvc_RedirectToRouteResult callInfo, int mid, SX.WebCore.Enums.ModelCoreType mct, System.Guid vid);

        [NonAction]
        public override System.Web.Mvc.RedirectToRouteResult DeleteMaterialVideo(int mid, SX.WebCore.Enums.ModelCoreType mct, System.Guid vid)
        {
            var callInfo = new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.DeleteMaterialVideo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mid", mid);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mct", mct);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vid", vid);
            DeleteMaterialVideoOverride(callInfo, mid, mct, vid);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
