//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GE.WebUI.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Sql_Articles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql_Articles() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GE.WebUI.Resources.Sql_Articles", typeof(Sql_Articles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT da.GameId,
        ///       dg.Title, dg.TitleUrl,
        ///       dg.FrontPictureId,
        ///       dg.[Description],
        ///       da.Name           AS ArticleTypeName,
        ///       da.[Description]  AS ArticleTypeDesc
        ///FROM   D_ARTICLE_TYPE da
        ///       JOIN D_GAME dg
        ///            ON  da.GameId = dg.ID
        ///WHERE  dg.FrontPictureid IS NOT NULL
        ///       AND dg.Show = 1
        ///GROUP BY
        ///       da.GameId,
        ///       dg.Title,dg.TitleUrl,
        ///       dg.FrontPictureid,
        ///       dg.[Description],
        ///       da.Name,
        ///       da.[Description]
        ///ORDER BY
        ///       d [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string FGBGameMenu {
            get {
                return ResourceManager.GetString("FGBGameMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --DECLARE @AMOUNT INT=3
        ///SELECT TOP(@AMOUNT) dm.TitleUrl, dm.Title, dm.DateCreate FROM D_ARTICLE AS da
        ///JOIN DV_MATERIAL AS dm ON dm.ID = da.ID AND dm.ModelCoreType = da.ModelCoreType
        ///ORDER BY dm.DateCreate DESC.
        /// </summary>
        public static string LastArticles {
            get {
                return ResourceManager.GetString("LastArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на --DECLARE @GAME_TITLE            VARCHAR(100) = &apos;dota2&apos;,
        ///--        @ARTICLE_TYPE_NAME     VARCHAR(150) = &apos;guid&apos;,
        ///--        @LETTERS_COUNT         INT = 200
        ///
        ///SELECT TOP(8) da.Id,
        ///       dm.Title,
        ///       dm.TitleUrl,
        ///       dm.DateCreate,
        ///       dm.ViewsCount,
        ///       dm.CommentsCount,
        ///       CASE 
        ///            WHEN dm.Foreword IS NOT NULL THEN dm.Foreword
        ///            ELSE SUBSTRING(dbo.FUNC_STRIP_HTML(dm.Html), 0, @LETTERS_COUNT) +
        ///                 &apos;...&apos;
        ///       END               AS Foreword
        ///FROM [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string PreviewMaterials {
            get {
                return ResourceManager.GetString("PreviewMaterials", resourceCulture);
            }
        }
    }
}
