//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GE.WebUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Sql_Articles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql_Articles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GE.WebUI.Resources.Sql_Articles", typeof(Sql_Articles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT da.GameId,
        ///       dg.Title, dg.TitleUrl,
        ///       dg.FrontPictureId,
        ///       dg.[Description],
        ///       da.Name           AS ArticleTypeName,
        ///       da.[Description]  AS ArticleTypeDesc
        ///FROM   D_ARTICLE_TYPE da
        ///       JOIN D_GAME dg
        ///            ON  da.GameId = dg.ID
        ///WHERE  dg.FrontPictureid IS NOT NULL
        ///       AND dg.Show = 1
        ///GROUP BY
        ///       da.GameId,
        ///       dg.Title,dg.TitleUrl,
        ///       dg.FrontPictureid,
        ///       dg.[Description],
        ///       da.Name,
        ///       da.[Description]
        ///ORDER BY
        ///       d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FGBGameMenu {
            get {
                return ResourceManager.GetString("FGBGameMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP(8) da.Id,
        ///       dm.Title,
        ///       dm.TitleUrl,
        ///       dm.DateCreate,
        ///       dm.DateOfPublication,
        ///       dm.ViewsCount,
        ///       dm.CommentsCount,
        ///       CASE 
        ///            WHEN dm.Foreword IS NOT NULL THEN dm.Foreword
        ///            ELSE SUBSTRING(dbo.FUNC_STRIP_HTML(dm.Html), 0, @LETTERS_COUNT) +
        ///                 &apos;...&apos;
        ///       END                    AS Foreword,
        ///       anu.NikName AS UserName,
        ///       dg.Title AS GameTitle
        ///FROM   D_ARTICLE              AS da
        ///       JOIN DV_MATERIAL       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PreviewMaterials {
            get {
                return ResourceManager.GetString("PreviewMaterials", resourceCulture);
            }
        }
    }
}
