//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SX.WebCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SX.WebCore.Resources.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SX Admin.
        /// </summary>
        public static string adminPanelName {
            get {
                return ResourceManager.GetString("adminPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v. 1.0.0.8.
        /// </summary>
        public static string adminPanelVersion {
            get {
                return ResourceManager.GetString("adminPanelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emptyGameBadImagePath.
        /// </summary>
        public static string emptyGameBadImagePath {
            get {
                return ResourceManager.GetString("emptyGameBadImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emptyGameGoodImagePath.
        /// </summary>
        public static string emptyGameGoodImagePath {
            get {
                return ResourceManager.GetString("emptyGameGoodImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to emptyGameIconPath.
        /// </summary>
        public static string emptyGameIconPath {
            get {
                return ResourceManager.GetString("emptyGameIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to robotsFileSetting.
        /// </summary>
        public static string robotsFileSetting {
            get {
                return ResourceManager.GetString("robotsFileSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to siteBgPath.
        /// </summary>
        public static string siteBgPath {
            get {
                return ResourceManager.GetString("siteBgPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to siteDomain.
        /// </summary>
        public static string siteDomain {
            get {
                return ResourceManager.GetString("siteDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to siteFaveiconPath.
        /// </summary>
        public static string siteFaveiconPath {
            get {
                return ResourceManager.GetString("siteFaveiconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to siteLogoPath.
        /// </summary>
        public static string siteLogoPath {
            get {
                return ResourceManager.GetString("siteLogoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to siteName.
        /// </summary>
        public static string siteName {
            get {
                return ResourceManager.GetString("siteName", resourceCulture);
            }
        }
    }
}
